project:
  type: website

website:
  title: "Planning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: jueves.qmd
        text: "24 Sep Jueves"
      - href: viernes.qmd
        text: "25 Sep Viernes"
      - href: sabado.qmd
        text: "26 Sep Sábado"
      - href: domingo.qmd
        text: "27 Sep Domingo"

format:
  html:
    toc: true
    theme:
      light: flatly
      dark: darkly